export const tripData = [
  {
    id: 1,
    owner: 'Mary',
    destination: 'Italy',
    date: '20-01-2023',
    comment: 'Funny trip',
  },
  {
    id: 2,
    owner: 'Daniel',
    destination: 'Paris',
    date: '14-02-2023',
    comment: 'Eiffel tower',
  },
  {
    id: 3,
    owner: 'Suzan',
    destination: 'Cyprus',
    date: '03-04-2023',
    comment: 'Sea trip',
  },
  {
    id: 4,
    owner: 'Mary1',
    destination: 'Italy',
    date: '20-01-2023',
    comment: 'Funny trip',
  },
  {
    id: 5,
    owner: 'Daniel1',
    destination: 'Paris',
    date: '14-02-2023',
    comment: 'Eiffel tower',
  },
  {
    id: 6,
    owner: 'Suzan1',
    destination: 'Cyprus',
    date: '03-04-2023',
    comment: 'Sea trip',
  },
  {
    id: 7,
    owner: 'Mary2',
    destination: 'Italy',
    date: '20-01-2023',
    comment: 'Funny trip',
  },
  {
    id: 8,
    owner: 'Daniel2',
    destination: 'Paris',
    date: '14-02-2023',
    comment: 'Eiffel tower',
  },
  {
    id: 9,
    owner: 'Suzan2',
    destination: 'Cyprus',
    date: '03-04-2023',
    comment: 'Sea trip',
  },
  {
    id: 10,
    owner: 'Mary3',
    destination: 'Italy',
    date: '20-01-2023',
    comment: 'Funny trip',
  },
  {
    id: 11,
    owner: 'Daniel3',
    destination: 'Paris',
    date: '14-02-2023',
    comment: 'Eiffel tower',
  },
  {
    id: 12,
    owner: 'Suzan3',
    destination: 'Cyprus',
    date: '03-04-2023',
    comment: 'Sea trip',
  },
];
