import kalahari from '../assets/images/countries/kalahari.jpg';
import sydney from '../assets/images/countries/sydney.jpg';
import yusendi from '../assets/images/countries/yusendi.jpg';
import user1 from '../assets/images/avatars/user1.jpg';
import user2 from '../assets/images/avatars/user2.jpg';
import user3 from '../assets/images/avatars/user3.jpg';

export const tripData = [
  {
    id: 1,
    owner: 'Mary',
    destination: 'Yusendi, Egypt',
    date: '20-01-2023',
    comment: 'Funny trip',
    avatar: user1,
    countryImg: yusendi,
    rating: 4.4,
    duration: '3-5',
  },
  {
    id: 2,
    owner: 'Daniel',
    destination: 'Paris',
    date: '14-02-2023',
    comment: 'Eiffel tower',
    avatar: user2,
    countryImg: yusendi,
    rating: 4.4,
    duration: '3-5',
  },
  {
    id: 3,
    owner: 'Suzan',
    destination: 'Cyprus',
    date: '03-04-2023',
    comment: 'Sea trip',
    avatar: user3,
    countryImg: yusendi,
    rating: 4.4,
    duration: '3-5',
  },
  {
    id: 4,
    owner: 'Mary1',
    destination: 'Yusendi, Egypt',
    date: '20-01-2023',
    comment: 'Funny trip',
    avatar: user1,
    countryImg: sydney,
    rating: 4.4,
    duration: '3-5',
  },
  {
    id: 5,
    owner: 'Daniel1',
    destination: 'Paris',
    date: '14-02-2023',
    comment: 'Eiffel tower',
    avatar: user2,
    countryImg: sydney,
    rating: 4.4,
    duration: '3-5',
  },
  {
    id: 6,
    owner: 'Suzan1',
    destination: 'Cyprus',
    date: '03-04-2023',
    comment: 'Sea trip',
    avatar: user3,
    countryImg: sydney,
    rating: 4.4,
    duration: '3-5',
  },
  {
    id: 7,
    owner: 'Mary2',
    destination: 'Yusendi, Egypt',
    date: '20-01-2023',
    comment: 'Funny trip',
    avatar: user1,
    countryImg: kalahari,
    rating: 4.4,
    duration: '3-5',
  },
  {
    id: 8,
    owner: 'Daniel2',
    destination: 'Paris',
    date: '14-02-2023',
    comment: 'Eiffel tower',
    avatar: user2,
    countryImg: kalahari,
    rating: 4.4,
    duration: '3-5',
  },
  {
    id: 9,
    owner: 'Suzan2',
    destination: 'Cyprus',
    date: '03-04-2023',
    comment: 'Sea trip',
    avatar: user3,
    countryImg: kalahari,
    rating: 4.4,
    duration: '3-5',
  },
  {
    id: 10,
    owner: 'Mary3',
    destination: 'Yusendi, Egypt',
    date: '20-01-2023',
    comment: 'Funny trip',
    avatar: user1,
    countryImg: yusendi,
    rating: 4.4,
    duration: '3-5',
  },
  {
    id: 11,
    owner: 'Daniel3',
    destination: 'Paris',
    date: '14-02-2023',
    comment: 'Eiffel tower',
    avatar: user2,
    countryImg: sydney,
    rating: 4.4,
    duration: '3-5',
  },
  {
    id: 12,
    owner: 'Suzan3',
    destination: 'Cyprus',
    date: '03-04-2023',
    comment: 'Sea trip',
    avatar: user3,
    countryImg: kalahari,
    rating: 4.4,
    duration: '3-5',
  },
];
